import { Sparkles, ThumbsUp, ShieldAlert, Target, Compass, ListChecks } from 'lucide-react'
import { Card } from '@/components/ui/Card'
import { PulseDot } from '@/components/ui/PulseDot'
import { Badge } from '@/components/ui/Badge'

// The AI Executive Summary. Sprint 10B: upgraded from a flat paragraph to
// structured sections (Overview / Key Wins / Key Risks / Growth
// Opportunities / Executive Recommendation / Next Steps), generated by
// services/executiveInsightEngine.js. Same card container/header as
// Sprint 10A so the surrounding Dashboard layout is unaffected.
function Section({ icon: Icon, title, children }) {
  return (
    <div className="mt-3 first:mt-0">
      <div className="mb-1 flex items-center gap-1.5">
        <Icon size={13} className="text-[var(--color-accent)]" />
        <p className="text-xs font-semibold uppercase tracking-wide text-[var(--color-muted)]">{title}</p>
      </div>
      {children}
    </div>
  )
}

export function ExecutiveSummaryCard({ insights }) {
  if (insights.isEmpty) {
    return (
      <Card className="border-[var(--color-accent)]/20 bg-gradient-to-br from-[var(--color-accent-soft)] to-transparent dark:from-[var(--color-accent-soft-dark)]">
        <div className="mb-2 flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[var(--color-accent)] text-white">
            <Sparkles size={14} />
          </div>
          <p className="text-sm font-semibold">AI Executive Summary</p>
        </div>
        <p className="text-sm text-[var(--color-muted)] dark:text-[var(--color-muted-dark)]">{insights.summary}</p>
      </Card>
    )
  }

  const ei = insights.executiveInsights

  return (
    <Card className="border-[var(--color-accent)]/20 bg-gradient-to-br from-[var(--color-accent-soft)] to-transparent dark:from-[var(--color-accent-soft-dark)]">
      <div className="mb-3 flex items-center gap-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[var(--color-accent)] text-white">
          <Sparkles size={14} />
        </div>
        <p className="text-sm font-semibold">{insights.headline}</p>
        <Badge variant="accent" className="ml-1">{insights.confidence} confidence</Badge>
        <PulseDot className="ml-auto" />
      </div>

      <Section icon={Compass} title="Overview">
        <p className="text-sm text-[var(--color-ink)] dark:text-[var(--color-ink-dark)]">{ei.overview}</p>
      </Section>

      <Section icon={ThumbsUp} title="Key Wins">
        <ul className="space-y-1 text-sm">
          {ei.keyWins.map((w, i) => <li key={i}>• {w}</li>)}
        </ul>
      </Section>

      <Section icon={ShieldAlert} title="Key Risks">
        <ul className="space-y-1 text-sm">
          {ei.keyRisks.map((r, i) => <li key={i}>• {r}</li>)}
        </ul>
      </Section>

      <Section icon={Target} title="Growth Opportunities">
        <ul className="space-y-1 text-sm">
          {ei.growthOpportunities.map((o, i) => <li key={i}>• {o}</li>)}
        </ul>
      </Section>

      <div className="mt-4 rounded-lg bg-white/60 p-3 dark:bg-white/5">
        <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-[var(--color-muted)]">Executive Recommendation</p>
        <p className="text-sm font-medium text-[var(--color-ink)] dark:text-[var(--color-ink-dark)]">{ei.executiveRecommendation}</p>
      </div>

      <Section icon={ListChecks} title="Next Steps">
        <ul className="space-y-1 text-sm">
          {ei.nextSteps.map((s, i) => <li key={i}>{i + 1}. {s}</li>)}
        </ul>
      </Section>
    </Card>
  )
}
