import { Sparkles } from 'lucide-react'
import { Card } from '@/components/ui/Card'
import { PulseDot } from '@/components/ui/PulseDot'

// The AI Executive Summary — top-of-Dashboard narrative. Sprint 10A: now
// generated by services/aiInsightEngine.js (Trend Analyzer + Opportunity
// Engine + Risk Analyzer + Period Comparison) instead of the older static
// executiveSummaryService output. Same card container/header as before so
// the surrounding Dashboard layout is unaffected — only the content source changed.
export function ExecutiveSummaryCard({ insights }) {
  if (insights.isEmpty) {
    return (
      <Card className="border-[var(--color-accent)]/20 bg-gradient-to-br from-[var(--color-accent-soft)] to-transparent dark:from-[var(--color-accent-soft-dark)]">
        <div className="mb-2 flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[var(--color-accent)] text-white">
            <Sparkles size={14} />
          </div>
          <p className="text-sm font-semibold">AI Executive Summary</p>
        </div>
        <p className="text-sm text-[var(--color-muted)] dark:text-[var(--color-muted-dark)]">{insights.summary}</p>
      </Card>
    )
  }

  return (
    <Card className="border-[var(--color-accent)]/20 bg-gradient-to-br from-[var(--color-accent-soft)] to-transparent dark:from-[var(--color-accent-soft-dark)]">
      <div className="mb-2 flex items-center gap-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[var(--color-accent)] text-white">
          <Sparkles size={14} />
        </div>
        <p className="text-sm font-semibold">{insights.headline}</p>
        <PulseDot className="ml-auto" />
      </div>

      <p className="text-sm text-[var(--color-ink)] dark:text-[var(--color-ink-dark)]">{insights.summary}</p>

      {insights.highlights.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-1.5">
          {insights.highlights.map((h, i) => (
            <span
              key={i}
              className="rounded-full bg-white/60 px-2.5 py-1 text-xs font-medium text-[var(--color-ink)] dark:bg-white/10 dark:text-[var(--color-ink-dark)]"
            >
              {h}
            </span>
          ))}
        </div>
      )}

      <div className="mt-4 border-t border-[var(--color-border)] pt-3 dark:border-[var(--color-border-dark)]">
        <p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--color-muted)]">Recommended Actions</p>
        <ul className="space-y-1 text-sm">
          {insights.recommendations.map((r, i) => (
            <li key={i} className="flex gap-2">
              <span className="text-[var(--color-accent)]">•</span>
              <span>{r}</span>
            </li>
          ))}
        </ul>
      </div>
    </Card>
  )
}
